sudo: required
language: node_js
services:
  - docker
node_js:
  - '8'
before_install:
  - sudo service mysql stop
  - sudo service postgresql stop
  - npm i -g npm@6
cache:
  directories:
    - 'node_modules'
    - 'client/node_modules'
    - 'server/node_modules'
install:
  - scripts/build.sh
script:
  - npm run lint
  - npm run test --prefix server
