sudo: required
language: node_js
services:
  - docker
node_js:
  - "6"
before_install:
  - sudo service mysql stop
  - sudo service postgresql stop
  - docker-compose pull
  - docker-compose up -d
  - npm i -g npm@5
cache:
  directories:
    - "client/node_modules"
    - "server/node_modules"
install:
  - npm ci --prefix server
  - npm ci --prefix client
jobs:
  include:
    - stage: lint client
      script: npm run lint --prefix client
    - stage: lint server
      script: npm run lint --prefix server
    - stage: test server
      script: npm run test --prefix server
