# This file is for development purposes
#
# You should be able to access the project 
#   http://localhost:3000 serving react files in dev mode via webpack
#   http://localhost:3010 serves compiled react files for production
#
# TODO add other supported databases where possible (crate, mssql, etc)
#
version: '3'
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
      - "3010:3010"
    links:
      - postgres
      - mariadb
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: sqlpad
      POSTGRES_DB: sqlpad
  mariadb:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: sqlpad
      MYSQL_DATABASE: sqlpad
      MYSQL_USER: sqlpad
      MYSQL_PASSWORD: sqlpad
  presto:
    image: johandry/presto:0.167-t.0.3-alpine
    expose: 
      - "8080"
    ports: 
      - "8080:8080"
    environment:
      HTTP_SERVER_PORT: 8080
      PRESTO_MAX_MEMORY: .25
      PRESTO_MAX_MEMORY_PER_NODE: .25
      PRESTO_JVM_HEAP_SIZE: 1
    links:
      - presto-worker
  presto-worker:
    image: johandry/presto:0.167-t.0.3-alpine
    environment:
      COORDINATOR: presto
      HTTP_SERVER_PORT: 8080
      PRESTO_MAX_MEMORY: .25
      PRESTO_MAX_MEMORY_PER_NODE: .25
      PRESTO_JVM_HEAP_SIZE: 1